[versions]
commons-math3 = "3.6.1"
guava = "32.1.2-jre"
junit-jupiter-engine = "5.10.0"
kotlin = "1.9.20"
exposed-core = "0.45.0"
ktor-server-core = "2.3.0"

[libraries]
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter-engine" }
exposed-core = {module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-core"}
ktor-server-core = {module = "io.ktor:ktor-server-core", version.ref = "ktor-server-core"}

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
